name: Deploy Website

on:
  push:
    branches:
      - master  # รันเมื่อ push branch master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # clone repo
      - uses: actions/checkout@v3

      # setup node
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # install dependencies
      - run: npm install

      # build project
      - run: npm run build

      # deploy to GitHub Pages
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/spa  # ชี้ folder SPA ของ Quasar
